version: '2'
services:
  nextcloud:
    image: nextcloud
    volumes:
      - nextcloudStore:/var/www/html
    ports:
      - "16000:80"
    environment:
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=database
    depends_on:
      - database
  database:
    image: mysql:5.7
    restart: always
    volumes:
      - databaseStore:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
volumes:
  nextcloudStore:
  databaseStore:
