# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  NpmTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [10.x, 12.x, 14.x]
        nodeversion: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.nodeversion }}
      #- name: Build and run the tests with Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodeversion }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
